document.addEventListener('DOMContentLoaded', function () {
    const quotes = [
        "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "Life is what happens when you're busy making other plans. - John Lennon",
        "Get busy living or get busy dying. - Stephen King",
        "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "The only impossible journey is the one you never begin. - Tony Robbins",
        "Act as if what you do makes a difference. It does. - William James",
        "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
        "Never bend your head. Always hold it high. Look the world straight in the eye. - Helen Keller",
        "What we think, we become. - Buddha",
        "Change your thoughts and you change your world. - Norman Vincent Peale",
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
        "You miss 100% of the shots you don’t take. - Wayne Gretzky",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "Everything you’ve ever wanted is on the other side of fear. - George Addair",
        "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
        "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
        "The best way to predict the future is to create it. - Peter Drucker",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
        "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
        "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
        "The secret of getting ahead is getting started. - Mark Twain",
        "It always seems impossible until it’s done. - Nelson Mandela",
        "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
        "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
        "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
        "If you can dream it, you can do it. - Walt Disney",
        "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
        "Don’t stop when you’re tired. Stop when you’re done. - Marilyn Monroe",
        "The way to get started is to quit talking and begin doing. - Walt Disney",
        "Don’t let yesterday take up too much of today. - Will Rogers",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
        "In the end, we only regret the chances we didn’t take. - Anonymous",
        "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
        "You must be the change you wish to see in the world. - Mahatma Gandhi",
        "Opportunities don't happen. You create them. - Chris Grosser",
        "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
        "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
        "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
        "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
        "The future belongs to those who prepare for it today. - Malcolm X",
        "The best revenge is massive success. - Frank Sinatra",
        "Don’t count the days, make the days count. - Muhammad Ali",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "The harder the conflict, the greater the triumph. - George Washington",
        "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
        "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
        "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
        "Aim for the moon. If you miss, you may hit a star. - W. Clement Stone",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
        "Keep going. Everything you need will come to you at the perfect time. - Anonymous",
        "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "Failure is the opportunity to begin again more intelligently. - Henry Ford",
        "The best way to get started is to quit talking and begin doing. - Walt Disney",
        "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
        "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
        "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. - Steve Jobs",
        "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
        "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
        "If you want to achieve greatness stop asking for permission. - Anonymous",
        "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
        "Do one thing every day that scares you. - Eleanor Roosevelt",
        "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
        "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
        "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
        "Success is not final, failure is not fatal
